@startuml

    actor User as u
    participant ListenerGclass as lgc
    participant ListenerDialogAttribute as lda
    participant "c : A_Class" as c
    participant "a : Attribute" as at

    u -> lgc: click add attribute
    activate lgc

    lgc -> lda: new ListenerDialogAttribute()
    activate lda
    lda --> lgc
    deactivate lda

    lgc --> u: add attributes form
    deactivate lgc

    loop for each attribute
        u -> lda: click add attribute
        activate lda
        u -> lda: String : name\nBoolean : static, final, derivated\nTypeBase\nVisibility
    end

    u -> lda: click OK

    loop for each attribute
        lda -> at: new Attribute(static, final, derivated, name, TypeBase, Visibility, c)
        activate at
        at --> lda
        deactivate at
        lda -> c: addAttribute(a)
        activate c
        c --> lda
        deactivate c
    end

    lda --> u: repainted view
    deactivate lda
@enduml