@startuml

    actor User as u
    participant ListenerDialogEditor as lde
    participant ListenerDialogBinaryRelation as ldbr
    participant A_ClassDiagram as Cd
    participant "r : BinaryRelation" as r
    participant "dmFrom : DoubleMultiplicity" as dmFrom
    participant "dmTo : DoubleMultiplicity" as dmTo
    participant "a : Association" as a
        
	u -> lde: Add binary relation click
	activate lde

        lde -> ldbr: new ListenerDialogBinaryRelation()
        activate ldbr
        ldbr --> lde
        deactivate ldbr

        lde --> u: Add binary relation form
        deactivate lde

        
        u -> ldbr: String : relationName,\nfromLabel, toLabel\nminValFrom, maxValFrom,\nminValTo, maxValTo,\nrelationType\nA_class : from, to
        activate ldbr

        opt
            u -> ldbr: A_class : associative
        end

        u -> ldbr: click OK

        ldbr -> r: new BinaryRelation(relationName)
        activate r
        r --> ldbr: r
        deactivate r

        ldbr -> dmFrom: new DoubleMultiplicity(minValFrom, maxValFrom, fromLabel, from)
        activate dmFrom
        dmFrom --> ldbr: dmFrom
        deactivate dmFrom
        
        ldbr -> dmTo: new DoubleMultiplicity(minValTo, maxValTo, toLabel, to)
        activate dmTo
        dmTo --> ldbr: dmTo
        deactivate dmTo

        ldbr -> r: updateMultiplicities(dmFrom, dmTo)
        activate r
        r --> ldbr
        deactivate r

        alt isDefined(associative)
           ldbr -> a: new Association(associative, r)
           activate a
           a --> ldbr: a
           deactivate a
           ldbr -> Cd: addRelation(a)
           activate Cd
           Cd --> ldbr
           deactivate Cd
        else
           ldbr -> Cd: addRelation(r)
           activate Cd
           Cd --> ldbr
           deactivate Cd
        end

        ldbr --> u: repainted view
        deactivate ldbr
@enduml