@startuml

    actor User as u
    participant ListenerEditor as le
    participant ListenerDialogClass as ldc
    participant A_ClassDiagram as Cd
    participant "p : A_Package" as p
    participant "c : A_Class" as c
    participant "lgc : ListenetGclass" as lgc
        
	u -> le: Add class click
	activate le
        le -> ldc: new ListenDialogClass()
        activate ldc
        ldc --> le
        deactivate ldc
        le --> u: New class form 
        deactivate le

        u -> ldc: String : className, packageName\n Boolean : final, static, abstract
        activate ldc
        u -> ldc: click OK
	ldc -> Cd: getListPackage()
        activate Cd
	Cd --> ldc: listPackage
        deactivate Cd

        ldc -> ldc: existsPackage(p)

	opt !existsPackage(p)
            ldc -> p: new A_Package(packageName)
            activate p
            p --> ldc
            deactivate p

            ldc -> ldc: listPackage.add(p)
	end
        
	ldc -> c: new A_Class(className, final, static, abstract, p)
        activate c
        c --> ldc
	deactivate c

        ldc -> p: addClass(c)
        activate p
        p --> ldc
        deactivate p
        
        ldc -> lgc: new ListenerGclass()
        activate lgc
        lgc --> ldc
        deactivate lgc

        ldc --> u: repainted view
@enduml