@startuml

    actor User as u
    participant ListenerEditor as le
    participant ListenerDialogClass as ldc
    participant A_ClassDiagram as Cd
    participant "p : A_Package" as p
    participant "c : A_Class" as c
    participant "lgc : ListenerGclass" as lgc
        
	u -> le: Add class click
	activate le
        le -> ldc: new ListenDialogClass()
        activate ldc
        ldc --> le
        deactivate ldc
        le --> u: New class form 
        deactivate le

        u -> ldc: String : className, packageName\n Boolean : final, static, abstract
        activate ldc
        u -> ldc: click OK
        
        ldc -> Cd: getListPackages()
        activate Cd
        Cd --> ldc: List<Package> lp
        deactivate Cd
        
        ldc -> ldc: lp.containsKey(packageName)

	opt !existsPackage(p, lp)
            ldc -> p: new A_Package(packageName)
            activate p
            p --> ldc: Package p
            deactivate p

            ldc -> Cd: addPackage(p)
            activate Cd
            Cd --> ldc
            deactivate Cd
	end
        
	ldc -> c: new A_Class(className, final, static, abstract, p)
        activate c
        c --> ldc: c
	deactivate c

        ldc -> p: addClass(c)
        activate p
        p --> ldc
        deactivate p
        
        ldc -> lgc: new ListenerGclass()
        activate lgc
        lgc --> ldc
        deactivate lgc

        ldc --> u: repainted view
@enduml