@startuml

    actor User as u
    participant Application as a
    participant A_ClassDiagram as Cd
    participant "p : A_Package" as p
    participant "i : An_Interface" as i

	u -> a: Add interface click
        activate a
        a --> u: information form
        u -> a: String : interfaceName, packageName

	a -> Cd: getListPackage()
        activate Cd
	Cd --> a: listPackage
        deactivate Cd

        a -> a: existsPackage(p)

	opt !existsPackage(p)
            a -> p: new A_Package(packageName)
            activate p
            p --> a
            deactivate p
            a -> a: listPackage.add(p)
	end

	a -> i: new An_Interface(interfaceName, p)
	activate i

	i --> a
	deactivate i

        a -> p: addInterface(i)
        activate p
        deactivate p
	deactivate a

@enduml