@startuml

    actor User as u
    participant ListenerGclass as lgc
    participant ListenerDialogMethodClass as lmc
    participant "c : A_Class" as c
    participant "m : Method" as m
    participant "p : Parameter" as p

    u -> lgc: click add method
    activate lgc

    lgc -> lmc : new ListenerDialogMethodClass()
    activate lmc
    lmc --> lgc
    deactivate lmc

    lgc --> u : add method to interface form
    deactivate lgc

    

    u -> lmc: String : name\nBoolean : static, final\nTypeRetour\nVisibility\n
    activate lmc
    loop for each parameter
        u -> lmc: click add parameter
        u -> lmc: String : name\nBoolean : final\nType
    end

    u -> lmc: click OK


    lmc -> m: new Method(Visibility, TypeRetour, String, boolean, boolean, c)
    activate m
    m --> lmc
    deactivate m
    loop for each parameter
        lmc -> p: new Parameter(name, final, Type)
        activate p
        p --> lmc
        deactivate p
        lmc -> m: addParameter(p)
        activate m
        m --> lmc
        deactivate m
    end
    deactivate m
    lmc -> c: addMethod(m)
    activate c
    c --> lmc
    deactivate c

    lmc --> u: repainted view
    deactivate lmc
@enduml