@startuml

    actor User as u
    participant ListenerGinterface as lgi
    participant ListenerDialogMethodInterface as lmi
    participant "i : An_Interface" as i
    participant "m : Method" as m
    participant "p : Parameter" as p

    u -> lgi: click add method
    activate lgi

    lgi -> lmi : new ListenerDialogMethodClass()
    activate lmi
    lmi --> lgi
    deactivate lmi

    lgi --> u : add method to interface form
    deactivate lgi

    

    u -> lmi: String : name\nBoolean : static, final\nTypeRetour\nVisibility\n
    activate lmi
    loop for each parameter
        u -> lmi: click add parameter
        u -> lmi: String : name\nBoolean : final\nType
    end

    u -> lmi: click OK


    lmi -> m: new Method(Visibility, TypeRetour, String, boolean, boolean, i)
    activate m
    m --> lmi
    deactivate m
    loop for each parameter
        lmi -> p: new Parameter(name, final, Type)
        activate p
        p --> lmi
        deactivate p
        lmi -> m: addParameter(p)
        activate m
        m --> lmi
        deactivate m
    end
    deactivate m
    lmi -> i: addMethod(m)
    activate i
    i --> lmi
    deactivate i

    lmi --> u: repainted view
    deactivate lmi
@enduml