@startuml

    actor User as u
    participant Application as a
    participant "p : A_Package" as p
    participant "i : An_Interface" as i

	u -> a: Remove class click\n String interfaceName
	activate a

	a -> i:
	activate i

	loop !listMethods.isEmpty()
		i -> i: removeMethod(Method)
	end

	i -> p: p.removeInterface(this)
	deactivate i

	p -> a
	a -> u
	deactivate a


@enduml