@startuml

    actor User as u
    participant Application as a
    participant "p : A_Package" as p
    participant "i : An_Interface" as i

        u -> a: Remove class click
	activate a

        a -> i: getClickedInterface()
        activate i

        i --> a: this
        deactivate i

	a -> i: getPackage()
	activate i
        i --> a: package
        deactivate i

	a -> p: removeInterface(i)
        activate p
        p -> p: listInterfaces.remove(i)
        p --> a
	deactivate p


@enduml