@startuml

    actor User as u
    participant Application as a
    participant "p : A_Package" as p
    participant "c : A_Class" as c

	u -> a: Remove class click
	activate a

        a -> c: getClickedClass()
        activate c

        c --> a: this
        deactivate c

	a -> c: getPackage()
	activate c
        c --> a: package
        deactivate c

	a -> p: removeClass(c)
        activate p
        p -> p: listClasses.remove(c)
        p --> a
	deactivate p


@enduml