@startuml

    actor User as u
    participant Application as a
    participant A_ClassDiagram as Cd
    participant "p : A_Package" as p

	u -> a: Add package / string PackageName
	a -> p: new A_Package(PackageName)
	activate p
	p -> a: return instance p
	activate a
	deactivate p
	a -> Cd : addPackage(p)
	activate Cd
	Cd -> Cd: listPackage.put(p)
	Cd -> a:
	deactivate Cd
	a -> u:
	deactivate a


@enduml