@startuml
    actor User as u
    participant UMLDiagram as uml
    participant A_ClassDiagram as Cd
    participant A_ObjectDiagram as Od

    u -> uml: launch the application / new UMLDiagram()
    activate uml
	    uml -> Cd: new A_ClassDiagram()
	    activate Cd
		    note right of Cd
		    	An instance of the class diagram is created
		    	when the application is started. Then the user
		    	can interact with his components.
		    end note
		    Cd -> uml: return A_ClassDiagram instance
	    deactivate Cd

	    uml -> Od: new A_ObjectDiagram()
	    activate Od
		    note right of Od
		    	An instance of the object diagram is created
		    	when the application is started. Then the user
		    	can interact with his components.
		    end note
		    Od -> uml: return A_ObjectDiagram instance
	    deactivate Od
    uml -> u: return UMLDiagram instance
    deactivate uml

@enduml