@startuml
skinparam packageStyle rect
left to right direction
:User: as Utilisateur

rectangle UML_Modeleur {

	rectangle systeme_diagramme_classe {
		
		(Ajouter une classe) as (ajouterClasse)
		(Ajouter une interface) as (ajouterInterface)
		(Ajouter une relation) as (ajouterRelationC)
		(Ajouter un package) as (ajouterPackage)
		
		(Supprimer une classe) as (supprimerClasse)
		(Supprimer une interface) as (supprimerInterface)
		(Supprimer une relation) as (supprimerrRelationC)
		(Supprimer un package) as (supprimerPackage)
		
	}

	Utilisateur -- (ajouterClasse)
	Utilisateur -- (ajouterInterface)
	Utilisateur -- (ajouterRelationC)
	Utilisateur -- (ajouterPackage)
	
	(ajouterClasse) <. (supprimerClasse) : extends
	(ajouterInterface) <. (supprimerInterface) : extends
	(ajouterRelationC) <. (supprimerrRelationC) : extends
	(ajouterPackage) <. (supprimerPackage) : extends


	rectangle systeme_diagramme_objet {
		(Ajouter un objet) as (ajouterObjet)
	    (Ajouter une relation) as (ajouterRelationO)
	    
	    (Supprimer un objet) as (supprimerObjet)
	    (Supprimer une relation) as (supprimerRelationO)
	    
	    (vérifier la cohérence du diagramme d'objet\navec le diagramme de classe) as (verifierDiagramme)
	}

	Utilisateur -- (ajouterObjet)
    Utilisateur -- (ajouterRelationO)
    (ajouterObjet) <. (supprimerObjet) : extends
    (ajouterRelationO) <. (supprimerRelationO) : extends
    
	Utilisateur -- (verifierDiagramme)

}

@enduml