@startuml
skinparam packageStyle rect
left to right direction
:User: as User

rectangle UML_Modeller {
	rectangle Class_Diagramm_System {
		(Create a class diagram) as (Class)
	}
	rectangle Object_Diagramm_System {
		(Create an object diagram) as (Object)
	}
   
    (Check coherence between\n class and objet diagrams) as (Coherence)

    User -- (Class)
    (Object) ..> (Class) : <<include>>
    User -- (Coherence)
}

@enduml