@startuml
skinparam packageStyle rect
left to right direction
:User:

rectangle UML_Modeleur {

	rectangle class diagram {
		(Manage classes) as (manageClasses)
		(Manage interfaces) as (manageInterfaces)
		(Manage relations between classes) as (manageRelationsC)
		(Manage packages) as (managePackages)	
	}

	User -- (manageClasses)
	User -- (manageInterfaces)
	User -- (manageRelationsC)
	User -- (managePackages)


	rectangle object diagram {
		(Manage objects) as (manageObjets)
		(Manage relations between objects) as (manageRelationsO)
	}

	User -- (manageObjets)
	User -- (manageRelationsO)
}

@enduml