@startuml

title Class diagram which models class diagrams

package model.class <<folder>> {

	package model.class.Classdiagram <<folder>> {
		 
		 class A_ClassDiagram {
		}	
	}
	
	
	package model.class.package <<folder>> {
		class Package {
		}
	}
	
	package model.class.relation <<folder>> {
		class Relation {
		}
	}

	A_ClassDiagram "1" *-- "1..*" Package
	A_ClassDiagram "1" *-- "1..*" Relation
		
}



@enduml