@startuml

title Class diagram which models relations

package model.class <<folder>> {

	package model.class.class <<folder>> {
		 
		 class A_class {
		  - name : String
		}
		
		
		abstract class Meta{
			- name : String
		}	
	}
	
	package model.class.interface <<folder>> {
		class An_Interface {
		  - name : String
		}
	}

	package model.class.relation <<folder>> {
			
			abstract class Relation{
				- title : String
			}
			
			abstract class BinaryRelation{
				- visibility : int
			}
		
			
			
			class Generalization {
			}	
		
		
			Generalization --|> Relation
			BinaryRelation --|> Relation
			
			Relation " " --* "1 from" A_class
			BinaryRelation " " --* "1 to" A_class
		
		
			abstract class BinaryRelationWithMultiplicity{
			}
			
			class Agregation {
			}
			
			
			class Composition {
			}
			note left: new composition(\n  new classA(), new singleMultiplicity(1),\n  new classB(), new DoubleMultiplicity(1,*)\n)
			class SimpleRelation {
			}
			
			class Association{
				Association contains a class
			}
			
			class Implementation {
			}
						
		}
		
		SimpleRelation --|> BinaryRelationWithMultiplicity
		Association --|> BinaryRelationWithMultiplicity
		Agregation --|> BinaryRelationWithMultiplicity
		Composition --|> BinaryRelationWithMultiplicity
		BinaryRelationWithMultiplicity --|> BinaryRelation
		Implementation " " --* "1" An_Interface
		Implementation --|> Relation
		
		
		
		
		package model.class.multiplicity <<folder>> {
			Abstract class Multiplicity{
			}
			
			class SingleMultiplicity{
				- value : int
			}	
			
			class DoubleMultiplicity{
				- maxValue : int
			}
			
			class NoMultiplicity{
			}	
		}
		
		SingleMultiplicity --|> Multiplicity
		DoubleMultiplicity --|> SingleMultiplicity
		NoMultiplicity --|> Multiplicity
	
		BinaryRelationWithMultiplicity " " --* "1 from" Multiplicity
		BinaryRelationWithMultiplicity " " --* "1 to" Multiplicity
		
		Association " " --* "1" A_class
		
		
		
		
		Generalization " " --* "1 from" Meta
		
		
		
}



@enduml