@startuml


	interface Observable {
		+ attache(Observateur)
		+ detache(Observateur)
		+ informe()
	}

	interface Observateur {
		+ misAJour()
	}


package model.class <<folder>> {

	package model.class.typedElement <<folder>> {

		class Attribute {
			- isDerivated : boolean

			+ Attribute(boolean, boolean, boolean,String, TypeBase, Visibility,Type)
			+ toString() : String
		}
	}
	package model.class.class <<folder>> {

		 class A_class {
		  - isFinal : boolean
		  - isStatic : boolean
		  - isAbstract : boolean

		  + A_class(String, boolean, boolean, boolean, A_Package)
		  + addMethod(Method) : void
		  + removeMethod(Method) : void
		  + addAttribute(Attribute) : void
		  + addAttribute(Attribute) : void
		  + toString() : String
		}
	}

	package model.class.relation <<folder>> {

	}

	package model.class.relation <<folder>> {
		class Relation {
		}
	}

	Relation --|> Observable
	Attribute --|> Observable
	A_class --|> Observable

	Relation "1" --> "*" Observateur
	Attribute "1" --> "*" Observateur
	A_class "1" --> "*" Observateur
}



package model.object.objectDiagram <<folder>> {

	 class Object {
	  - name : String
	 }

	 abstract class RelationO{
		- title : String
	}

	package model.object.value <<folder>> {

		 abstract class Value {
		   + toString() : String
		 }

		 class IntValue {
		  - value : int
		 }
		 class FloatValue {
		   - value : float
		 }
		 class DoubleValue {
		   - value : double
		 }
		 class StringValue {
		   - value : String
		 }
		 class BooleanValue {
		   - value : boolean
		 }

	}

	RelationO  --> "1" Relation
	A_class "1" <-- Object
	Object --> "*" RelationO
	Object --* "*" Value

	Value --> "1" Attribute

	IntValue --|> Value
	FloatValue --|> Value
	DoubleValue --|> Value
	StringValue --|> Value
	BooleanValue --|> Value

	Value --|> Observateur
	RelationO --|> Observateur
	Object --|> Observateur
}






@enduml