@startuml
skinparam packageStyle rect
left to right direction
actor User

rectangle UML_Modeler {

	rectangle class_diagram {
		(Manage classes) as (manageClasses)
		(Manage interfaces) as (manageInterfaces)
		(Manage relations between classes) as (manageRelationsC)
	}

	User -- (manageClasses)
	User -- (manageInterfaces)
	User -- (manageRelationsC)


	rectangle object_diagram {
		(Manage objects) as (manageObjets)
		(Manage relations between objects) as (manageRelationsO)
	}

	User -- (manageObjets)
	User -- (manageRelationsO)
}

@enduml