@startuml
actor User
participant System

User -> System: Add Method
System -> User: name, return type, visibility, parameters ?
User -> System: name, return type, visibility, parameters
loop for each parameter
	System -> User: type, name ?
	User -> System: type, name
end

@enduml