@startuml
actor User
participant System

loop
    opt
        User -> System: Add class
    end
    opt
        User -> System: Add interface
    end
    opt
        alt class + interface >= 3
            User -> System: Add n-ary relation
        end
        alt class + interface >= 2
            User -> System: Add binary relation
        end
    end
end
@enduml