@startuml
    actor User as u
    participant System as s

    opt number of existing class >= 1
        u -> s: add a binary relation
        loop !validation
            s -> u: information demand
            u --> s: type, classes, visibily, cardinality
        end
    end

    opt number of existing class >= 2
        u -> s: add a n-ary relation
        loop !validation
            s -> u: information demand
            u --> s: classes, visibily, cardinality, type
        end
    end
@enduml