@startuml
    actor User as U
    participant System as S

    U -> S: add an interface
    loop !validation
        S -> U: informations demand
        U --> S: name, package
    end

    loop
        U -> S: add a method
        loop !validation
            S -> U: information demand
            U --> S: name, type, visibility, parameters
        end
    end
    
@enduml