@startuml

package model.class <<folder>> {

	package model.class.typedElement <<folder>> {

		class Attribute {
		}
	}
	package model.class.class <<folder>> {

		 class A_class {
		}
	}

	package model.class.relation <<folder>> {

	}

	package model.class.relation <<folder>> {
		class Relation {
		}
	}
}



package model.object.objectDiagram <<folder>> {

	 class Object {
	  - name : String
	 }

	 abstract class RelationO{
		- title : String
	}

	package model.object.value <<folder>> {

		 abstract class Value {
		 }

		 class IntValue {
		  - value : int
		 }
		 class FloatValue {
		   - value : float
		 }
		 class DoubleValue {
		   - value : double
		 }
		 class StringValue {
		   - value : String
		 }
		 class BooleanValue {
		   - value : boolean
		 }

	}

	RelationO "1..*" --> "1" Relation
	A_class "1" <-- "1..*" Object
	Object --> "1..*" RelationO
	Object "1" *-- "*" Value

	Value "1..*" --> "1" Attribute

	IntValue --|> Value
	FloatValue --|> Value
	DoubleValue --|> Value
	StringValue --|> Value
	BooleanValue --|> Value

}






@enduml